_wandb:
    value:
        cli_version: 0.25.1
        e:
            ch03rti6ytka74fg0jm4c136g83dfs6h:
                codePath: src/train.py
                codePathLocal: train.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "53607378944"
                        used: "46288605184"
                email: hanz5@andrew.cmu.edu
                executable: /home/ec2-user/miniconda3/envs/instructp2p/bin/python3
                git:
                    commit: 71d821196ebcb3d5b1befe03e00fd3d122df8698
                    remote: git@github.com:carnegieJiang/GenAI-Project.git
                gpu: NVIDIA A10G
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "24146608128"
                      name: NVIDIA A10G
                      uuid: GPU-935cc1b8-f129-af1d-ea10-ef2afcdc7dc1
                host: ip-172-31-41-150.ec2.internal
                memory:
                    total: "33267298304"
                os: Linux-6.1.163-186.299.amzn2023.x86_64-x86_64-with-glibc2.34
                program: /home/ec2-user/GenAI-Project/src/train.py
                python: CPython 3.10.20
                root: /home/ec2-user/GenAI-Project/src
                startedAt: "2026-04-11T07:46:28.223171Z"
                writerId: ch03rti6ytka74fg0jm4c136g83dfs6h
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
            "3":
                - 16
                - 61
            "4": 3.10.20
            "5": 0.25.1
            "6": 5.5.3
            "12": 0.25.1
            "13": linux-x86_64
batch_size:
    value: 4
data_path:
    value: /home/ec2-user/GenAI-Project/data/stylebooth_subset/metadata.csv
freeze_text_encoder:
    value: false
freeze_vae:
    value: false
grad_accum_steps:
    value: 1
lr:
    value: 1e-05
max_grad_norm:
    value: 1
mixed_precision:
    value: "no"
num_epochs:
    value: 10
num_sample_images:
    value: 4
num_workers:
    value: 4
output_dir:
    value: /home/ec2-user/GenAI-Project/model/diffusion_outputs
prompt_dropout_prob:
    value: 0.1
resolution:
    value: 512
sample_every_steps:
    value: 500
save_every_steps:
    value: 1000
seed:
    value: 42
weight_decay:
    value: 0.01
